name: Build Desktop Packages

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build-desktop:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant permissions for Gradle wrapper
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
        
      - name: Build package
        run: ./gradlew :composeApp:packageReleaseDistributionForCurrentOS
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ runner.os }}-${{ github.run_number }}
          path: |
            composeApp/build/compose/binaries/main/dmg/
            composeApp/build/compose/binaries/main/msi/
            composeApp/build/compose/binaries/main/deb/
          if-no-files-found: ignore
          retention-days: 30
